spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/concurrency_test?useUnicode=true&amp;characterEncoding=UTF8&amp; zeroDateTimeBehavior=convertToNull&amp;transformedBitIsBoolean=true&allowMultiQueries=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    qct: debug
    #show sql statement
    org.hibernate.SQL: debug
    #show sql values
    org.hibernate.type.descriptor.sql: trace
